//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("VentasModel", "FK_Detalle_Articulo", "Articulos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VentasWS.Models.Articulo), "Detalle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VentasWS.Models.Detalle), true)]
[assembly: EdmRelationshipAttribute("VentasModel", "FK_Factura_Cliente", "Clientes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VentasWS.Models.Cliente), "Factura", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VentasWS.Models.Factura), true)]
[assembly: EdmRelationshipAttribute("VentasModel", "FK_Detalle_Factura", "Factura", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VentasWS.Models.Factura), "Detalle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VentasWS.Models.Detalle), true)]

#endregion

namespace VentasWS.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class VentasEntities4 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new VentasEntities4 object using the connection string found in the 'VentasEntities4' section of the application configuration file.
        /// </summary>
        public VentasEntities4() : base("name=VentasEntities4", "VentasEntities4")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VentasEntities4 object.
        /// </summary>
        public VentasEntities4(string connectionString) : base(connectionString, "VentasEntities4")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VentasEntities4 object.
        /// </summary>
        public VentasEntities4(EntityConnection connection) : base(connection, "VentasEntities4")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Articulo> Articulos
        {
            get
            {
                if ((_Articulos == null))
                {
                    _Articulos = base.CreateObjectSet<Articulo>("Articulos");
                }
                return _Articulos;
            }
        }
        private ObjectSet<Articulo> _Articulos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cliente> Clientes
        {
            get
            {
                if ((_Clientes == null))
                {
                    _Clientes = base.CreateObjectSet<Cliente>("Clientes");
                }
                return _Clientes;
            }
        }
        private ObjectSet<Cliente> _Clientes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Detalle> Detalles
        {
            get
            {
                if ((_Detalles == null))
                {
                    _Detalles = base.CreateObjectSet<Detalle>("Detalles");
                }
                return _Detalles;
            }
        }
        private ObjectSet<Detalle> _Detalles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Factura> Facturas
        {
            get
            {
                if ((_Facturas == null))
                {
                    _Facturas = base.CreateObjectSet<Factura>("Facturas");
                }
                return _Facturas;
            }
        }
        private ObjectSet<Factura> _Facturas;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Articulos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToArticulos(Articulo articulo)
        {
            base.AddObject("Articulos", articulo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Clientes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClientes(Cliente cliente)
        {
            base.AddObject("Clientes", cliente);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Detalles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDetalles(Detalle detalle)
        {
            base.AddObject("Detalles", detalle);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Facturas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFacturas(Factura factura)
        {
            base.AddObject("Facturas", factura);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VentasModel", Name="Articulo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Articulo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Articulo object.
        /// </summary>
        /// <param name="codigo_Articulo">Initial value of the Codigo_Articulo property.</param>
        /// <param name="nombre_Articulo">Initial value of the Nombre_Articulo property.</param>
        /// <param name="precio_Articulo">Initial value of the Precio_Articulo property.</param>
        /// <param name="iVA">Initial value of the IVA property.</param>
        /// <param name="total">Initial value of the Total property.</param>
        public static Articulo CreateArticulo(global::System.Int32 codigo_Articulo, global::System.String nombre_Articulo, global::System.Decimal precio_Articulo, global::System.Decimal iVA, global::System.Decimal total)
        {
            Articulo articulo = new Articulo();
            articulo.Codigo_Articulo = codigo_Articulo;
            articulo.Nombre_Articulo = nombre_Articulo;
            articulo.Precio_Articulo = precio_Articulo;
            articulo.IVA = iVA;
            articulo.Total = total;
            return articulo;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Codigo_Articulo
        {
            get
            {
                return _Codigo_Articulo;
            }
            set
            {
                if (_Codigo_Articulo != value)
                {
                    OnCodigo_ArticuloChanging(value);
                    ReportPropertyChanging("Codigo_Articulo");
                    _Codigo_Articulo = StructuralObject.SetValidValue(value, "Codigo_Articulo");
                    ReportPropertyChanged("Codigo_Articulo");
                    OnCodigo_ArticuloChanged();
                }
            }
        }
        private global::System.Int32 _Codigo_Articulo;
        partial void OnCodigo_ArticuloChanging(global::System.Int32 value);
        partial void OnCodigo_ArticuloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre_Articulo
        {
            get
            {
                return _Nombre_Articulo;
            }
            set
            {
                OnNombre_ArticuloChanging(value);
                ReportPropertyChanging("Nombre_Articulo");
                _Nombre_Articulo = StructuralObject.SetValidValue(value, false, "Nombre_Articulo");
                ReportPropertyChanged("Nombre_Articulo");
                OnNombre_ArticuloChanged();
            }
        }
        private global::System.String _Nombre_Articulo;
        partial void OnNombre_ArticuloChanging(global::System.String value);
        partial void OnNombre_ArticuloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Precio_Articulo
        {
            get
            {
                return _Precio_Articulo;
            }
            set
            {
                OnPrecio_ArticuloChanging(value);
                ReportPropertyChanging("Precio_Articulo");
                _Precio_Articulo = StructuralObject.SetValidValue(value, "Precio_Articulo");
                ReportPropertyChanged("Precio_Articulo");
                OnPrecio_ArticuloChanged();
            }
        }
        private global::System.Decimal _Precio_Articulo;
        partial void OnPrecio_ArticuloChanging(global::System.Decimal value);
        partial void OnPrecio_ArticuloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal IVA
        {
            get
            {
                return _IVA;
            }
            set
            {
                OnIVAChanging(value);
                ReportPropertyChanging("IVA");
                _IVA = StructuralObject.SetValidValue(value, "IVA");
                ReportPropertyChanged("IVA");
                OnIVAChanged();
            }
        }
        private global::System.Decimal _IVA;
        partial void OnIVAChanging(global::System.Decimal value);
        partial void OnIVAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = StructuralObject.SetValidValue(value, "Total");
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private global::System.Decimal _Total;
        partial void OnTotalChanging(global::System.Decimal value);
        partial void OnTotalChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VentasModel", "FK_Detalle_Articulo", "Detalle")]
        public EntityCollection<Detalle> Detalles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Detalle>("VentasModel.FK_Detalle_Articulo", "Detalle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Detalle>("VentasModel.FK_Detalle_Articulo", "Detalle", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VentasModel", Name="Cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cliente : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cliente object.
        /// </summary>
        /// <param name="id_Cliente">Initial value of the Id_Cliente property.</param>
        /// <param name="nombre_Cliente">Initial value of the Nombre_Cliente property.</param>
        /// <param name="usuario">Initial value of the Usuario property.</param>
        /// <param name="contrasena">Initial value of the Contrasena property.</param>
        public static Cliente CreateCliente(global::System.Int32 id_Cliente, global::System.String nombre_Cliente, global::System.String usuario, global::System.String contrasena)
        {
            Cliente cliente = new Cliente();
            cliente.Id_Cliente = id_Cliente;
            cliente.Nombre_Cliente = nombre_Cliente;
            cliente.Usuario = usuario;
            cliente.Contrasena = contrasena;
            return cliente;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Cliente
        {
            get
            {
                return _Id_Cliente;
            }
            set
            {
                if (_Id_Cliente != value)
                {
                    OnId_ClienteChanging(value);
                    ReportPropertyChanging("Id_Cliente");
                    _Id_Cliente = StructuralObject.SetValidValue(value, "Id_Cliente");
                    ReportPropertyChanged("Id_Cliente");
                    OnId_ClienteChanged();
                }
            }
        }
        private global::System.Int32 _Id_Cliente;
        partial void OnId_ClienteChanging(global::System.Int32 value);
        partial void OnId_ClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre_Cliente
        {
            get
            {
                return _Nombre_Cliente;
            }
            set
            {
                OnNombre_ClienteChanging(value);
                ReportPropertyChanging("Nombre_Cliente");
                _Nombre_Cliente = StructuralObject.SetValidValue(value, false, "Nombre_Cliente");
                ReportPropertyChanged("Nombre_Cliente");
                OnNombre_ClienteChanged();
            }
        }
        private global::System.String _Nombre_Cliente;
        partial void OnNombre_ClienteChanging(global::System.String value);
        partial void OnNombre_ClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Usuario
        {
            get
            {
                return _Usuario;
            }
            set
            {
                OnUsuarioChanging(value);
                ReportPropertyChanging("Usuario");
                _Usuario = StructuralObject.SetValidValue(value, false, "Usuario");
                ReportPropertyChanged("Usuario");
                OnUsuarioChanged();
            }
        }
        private global::System.String _Usuario;
        partial void OnUsuarioChanging(global::System.String value);
        partial void OnUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Contrasena
        {
            get
            {
                return _Contrasena;
            }
            set
            {
                OnContrasenaChanging(value);
                ReportPropertyChanging("Contrasena");
                _Contrasena = StructuralObject.SetValidValue(value, false, "Contrasena");
                ReportPropertyChanged("Contrasena");
                OnContrasenaChanged();
            }
        }
        private global::System.String _Contrasena;
        partial void OnContrasenaChanging(global::System.String value);
        partial void OnContrasenaChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VentasModel", "FK_Factura_Cliente", "Factura")]
        public EntityCollection<Factura> Facturas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Factura>("VentasModel.FK_Factura_Cliente", "Factura");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Factura>("VentasModel.FK_Factura_Cliente", "Factura", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VentasModel", Name="Detalle")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Detalle : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Detalle object.
        /// </summary>
        /// <param name="id_Detalle">Initial value of the Id_Detalle property.</param>
        /// <param name="id_Factura">Initial value of the Id_Factura property.</param>
        /// <param name="codigo_Articulo">Initial value of the Codigo_Articulo property.</param>
        /// <param name="cantidad">Initial value of the Cantidad property.</param>
        /// <param name="total">Initial value of the Total property.</param>
        public static Detalle CreateDetalle(global::System.Int32 id_Detalle, global::System.Int32 id_Factura, global::System.Int32 codigo_Articulo, global::System.Decimal cantidad, global::System.Decimal total)
        {
            Detalle detalle = new Detalle();
            detalle.Id_Detalle = id_Detalle;
            detalle.Id_Factura = id_Factura;
            detalle.Codigo_Articulo = codigo_Articulo;
            detalle.Cantidad = cantidad;
            detalle.Total = total;
            return detalle;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Detalle
        {
            get
            {
                return _Id_Detalle;
            }
            set
            {
                if (_Id_Detalle != value)
                {
                    OnId_DetalleChanging(value);
                    ReportPropertyChanging("Id_Detalle");
                    _Id_Detalle = StructuralObject.SetValidValue(value, "Id_Detalle");
                    ReportPropertyChanged("Id_Detalle");
                    OnId_DetalleChanged();
                }
            }
        }
        private global::System.Int32 _Id_Detalle;
        partial void OnId_DetalleChanging(global::System.Int32 value);
        partial void OnId_DetalleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Factura
        {
            get
            {
                return _Id_Factura;
            }
            set
            {
                OnId_FacturaChanging(value);
                ReportPropertyChanging("Id_Factura");
                _Id_Factura = StructuralObject.SetValidValue(value, "Id_Factura");
                ReportPropertyChanged("Id_Factura");
                OnId_FacturaChanged();
            }
        }
        private global::System.Int32 _Id_Factura;
        partial void OnId_FacturaChanging(global::System.Int32 value);
        partial void OnId_FacturaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Codigo_Articulo
        {
            get
            {
                return _Codigo_Articulo;
            }
            set
            {
                OnCodigo_ArticuloChanging(value);
                ReportPropertyChanging("Codigo_Articulo");
                _Codigo_Articulo = StructuralObject.SetValidValue(value, "Codigo_Articulo");
                ReportPropertyChanged("Codigo_Articulo");
                OnCodigo_ArticuloChanged();
            }
        }
        private global::System.Int32 _Codigo_Articulo;
        partial void OnCodigo_ArticuloChanging(global::System.Int32 value);
        partial void OnCodigo_ArticuloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Cantidad
        {
            get
            {
                return _Cantidad;
            }
            set
            {
                OnCantidadChanging(value);
                ReportPropertyChanging("Cantidad");
                _Cantidad = StructuralObject.SetValidValue(value, "Cantidad");
                ReportPropertyChanged("Cantidad");
                OnCantidadChanged();
            }
        }
        private global::System.Decimal _Cantidad;
        partial void OnCantidadChanging(global::System.Decimal value);
        partial void OnCantidadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Total
        {
            get
            {
                return _Total;
            }
            set
            {
                OnTotalChanging(value);
                ReportPropertyChanging("Total");
                _Total = StructuralObject.SetValidValue(value, "Total");
                ReportPropertyChanged("Total");
                OnTotalChanged();
            }
        }
        private global::System.Decimal _Total;
        partial void OnTotalChanging(global::System.Decimal value);
        partial void OnTotalChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VentasModel", "FK_Detalle_Articulo", "Articulos")]
        public Articulo Articulo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Articulo>("VentasModel.FK_Detalle_Articulo", "Articulos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Articulo>("VentasModel.FK_Detalle_Articulo", "Articulos").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Articulo> ArticuloReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Articulo>("VentasModel.FK_Detalle_Articulo", "Articulos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Articulo>("VentasModel.FK_Detalle_Articulo", "Articulos", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VentasModel", "FK_Detalle_Factura", "Factura")]
        public Factura Factura
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Factura>("VentasModel.FK_Detalle_Factura", "Factura").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Factura>("VentasModel.FK_Detalle_Factura", "Factura").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Factura> FacturaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Factura>("VentasModel.FK_Detalle_Factura", "Factura");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Factura>("VentasModel.FK_Detalle_Factura", "Factura", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VentasModel", Name="Factura")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Factura : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Factura object.
        /// </summary>
        /// <param name="id_Factura">Initial value of the Id_Factura property.</param>
        /// <param name="id_Cliente">Initial value of the Id_Cliente property.</param>
        /// <param name="fecha">Initial value of the Fecha property.</param>
        public static Factura CreateFactura(global::System.Int32 id_Factura, global::System.Int32 id_Cliente, global::System.DateTime fecha)
        {
            Factura factura = new Factura();
            factura.Id_Factura = id_Factura;
            factura.Id_Cliente = id_Cliente;
            factura.Fecha = fecha;
            return factura;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Factura
        {
            get
            {
                return _Id_Factura;
            }
            set
            {
                if (_Id_Factura != value)
                {
                    OnId_FacturaChanging(value);
                    ReportPropertyChanging("Id_Factura");
                    _Id_Factura = StructuralObject.SetValidValue(value, "Id_Factura");
                    ReportPropertyChanged("Id_Factura");
                    OnId_FacturaChanged();
                }
            }
        }
        private global::System.Int32 _Id_Factura;
        partial void OnId_FacturaChanging(global::System.Int32 value);
        partial void OnId_FacturaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id_Cliente
        {
            get
            {
                return _Id_Cliente;
            }
            set
            {
                OnId_ClienteChanging(value);
                ReportPropertyChanging("Id_Cliente");
                _Id_Cliente = StructuralObject.SetValidValue(value, "Id_Cliente");
                ReportPropertyChanged("Id_Cliente");
                OnId_ClienteChanged();
            }
        }
        private global::System.Int32 _Id_Cliente;
        partial void OnId_ClienteChanging(global::System.Int32 value);
        partial void OnId_ClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value, "Fecha");
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VentasModel", "FK_Factura_Cliente", "Clientes")]
        public Cliente Cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("VentasModel.FK_Factura_Cliente", "Clientes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("VentasModel.FK_Factura_Cliente", "Clientes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cliente> ClienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("VentasModel.FK_Factura_Cliente", "Clientes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cliente>("VentasModel.FK_Factura_Cliente", "Clientes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VentasModel", "FK_Detalle_Factura", "Detalle")]
        public EntityCollection<Detalle> Detalles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Detalle>("VentasModel.FK_Detalle_Factura", "Detalle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Detalle>("VentasModel.FK_Detalle_Factura", "Detalle", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
